/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // === DESIGN.md exact tokens ===
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e8bdb6',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'outline': '#ae8882',
        'outline-variant': '#5e3f3a',
        'surface-tint': '#ffb4a8',
        'primary': '#ffb4a8',
        'on-primary': '#690000',
        'primary-container': '#cc0000',
        'on-primary-container': '#ffdad4',
        'inverse-primary': '#c00000',
        'primary-fixed': '#ffdad4',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary-fixed': '#410000',
        'on-primary-fixed-variant': '#930000',
        'secondary': '#c6c6c6',
        'on-secondary': '#303030',
        'secondary-container': '#474747',
        'on-secondary-container': '#b5b5b5',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#1b1b1b',
        'on-secondary-fixed-variant': '#474747',
        'tertiary': '#c6c6c7',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#636565',
        'on-tertiary-container': '#e2e3e3',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
        // Utility aliases
        'border-default': '#333333',
      },
      fontFamily: {
        'display': ['Bebas Neue', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
      spacing: {
        'section-gap': '120px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'gutter': '24px',
        'container-max': '1280px',
      },
      fontSize: {
        'display-lg': ['80px', { lineHeight: '80px', letterSpacing: '0.02em' }],
        'headline-lg': ['48px', { lineHeight: '48px', letterSpacing: '0.02em' }],
        'headline-md': ['32px', { lineHeight: '32px', letterSpacing: '0.02em' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em' }],
      },
      maxWidth: {
        'container': '1280px',
      }
    },
  },
  plugins: [],
}
